### ISSUE TITLE
Miner Fails To Install (HiveOS)

### ISSUE THREAD

**Issue by petrovsky34** [MaynardMiner/SWARM#116]
Unable to install miner from https://github.com/MaynardMine
![FireShot Capture 002 - Workers - Miner - the hiveos farm](https://user-images.githubusercontent.com/39003568/56867965-c11a6e80-69db-11e9-957f-c0e3fdbf44d8.png)
r/SWARM/releases/download/v2.2.0/SWARM.2.2.0.tar.gz

**Comment by petrovsky34** [comment]
Unable to install miner from https://github.com/MaynardMiner/SWARM/releases/download/v2.2.0/SWARM.2.2.0.tar.gz

**Comment by petrovsky34** [comment]
![FireShot Capture 003 - Flight Sheets - Miner - the hiveos farm](https://user-images.githubusercontent.com/39003568/56867983-edce8600-69db-11e9-8c0a-01a36793f643.png)

**Comment by petrovsky34** [comment]
-RigName1 1054 -RigName2 1063 -Currency RUB -Location EUROPE -PoolName zergpool,nicehash -Type NVIDIA1,NVIDIA2 -Nicehash_Wallet1 36QFg44C35w2job1yJwkgP16sCFYCJt8jU -Nicehash_Wallet2 36QFg44C35w2job1yJwkgP16sCFYCJt8jU -Wallet1 Xb6b1dtNAbV7epmA7JiVEwmboN9fkxryRa -Wallet2 Xb6b1dtNAbV7epmA7JiVEwmboN9fkxryRa -PasswordCurrency1 DASH -PasswordCurrency2 DASH -Benchmark 120 -Interval 60 -Update yes -GPUDevices1 0,1,2,3,4,5,8,9 -GPUDevices2 6,7 -Auto_Coin yes -donate 5

**Comment by petrovsky34** [comment]
![FireShot Capture 004 - Flight Sheets - Miner - the hiveos farm](https://user-images.githubusercontent.com/39003568/56868003-2e2e0400-69dc-11e9-8964-4cd4557775cb.png)

**Comment by petrovsky34** [comment]
according to your instructions does not work(((

**Comment by petrovsky34** [comment]
![FireShot Capture 005 - Flight Sheets - Miner - the hiveos farm](https://user-images.githubusercontent.com/39003568/56868061-fffcf400-69dc-11e9-881f-ea7473c257ad.png)

**Comment by MaynardMiner** [comment]
I apologize for the delay. I don't check github often. I am going to run a test, and see why it is failing. Your settings to install look correct.

**Comment by MaynardMiner** [comment]
It appears the link is working for me.

try removing previous downloads. You may have had a bad downloads:

``miner stop``
``remove -rf /hive/miners/custom/downloads/*``
``miner start``

then try run

**Comment by MaynardMiner** [comment]
If that doesn't work, you can manually download

``wget https://github.com/MaynardMiner/SWARM/releases/download/v2.2.0/SWARM.2.2.0.tar.gz``

Then manually extract the file to ``/hive/miners/custom`` as ``SWARM.2.2.0``, so the end path is:

``/hive/miners/custom/SWARM.2.2.0``

Then you remove the url from flight, sheet.

Attempting to do that, one step at a time, will likely determine what issue is.

**Comment by MaynardMiner** [comment]
It was the .git, it was causing issues with extraction. Another user discovered.

I removed the .git file from the release. It should work.

**Comment by erdrickk** [comment]
I'm getting a similar error - latest Swarm / HiveOs installed  https://prnt.sc/nifvqk

**Comment by MaynardMiner** [comment]
@erdrickk 

Can I see a post of the arguments you are using?

**Comment by erdrickk** [comment]
I'm just using the sample arguments to test it out - let me know if I have to change anything!
http://prntscr.com/nigte4

**Comment by MaynardMiner** [comment]
The []   are just place holders. Removed them where applicable.

Also, you have to choose a location closest to you. You can't use all three. SWARM will use the nearest stratum location to you available for each pool.

**Comment by erdrickk** [comment]
what's the difference between NVIDIA1 and NVIDIA2?

**Comment by MaynardMiner** [comment]
```
Items inside of [brackets] are meant to be selected by user. The brackets[] should be removed

-RigName1 SWARM -Location [Choose one: US or Europe or Asia] -PoolName [Choose Any Number Of Pools nlpool,blockmasters,nicehash,starpool,ahashpool,blazepool,hashrefinery,phiphipool,zpool] -Type [Choose where applicable: [AMD1] or [NVIDIA1] or [AMD1,NVIDIA2]] -Wallet1 [Your BTC Wallet] -Donate .5
```
I changed in wiki to prevent confusion.

There is a help file on arguments:

https://github.com/MaynardMiner/SWARM/blob/master/help/SWARM_help.txt

Essentially, you can divide your miner up to three ways. Also, if you had a hybrid AMD/NVIDIA setup, you would use ``-Type AMD1,NVIDIA2``

**Comment by MaynardMiner** [comment]
I also just added zergpool and fairpool, and removed starpool (Gone).

I also added nicehash. Those can be used with basic setting now, however you can specify a nicehash wallet, and other nicehash specific settings.
