### ISSUE TITLE
add eth pool

### ISSUE THREAD

**Issue by petrovsky34** [MaynardMiner/SWARM#126]
https://ethashpool.com/

**Comment by MaynardMiner** [comment]
It is PPLNS payments though. Not good for switching...

It is why I do not use Mining Pool Hub as well.

**Comment by MaynardMiner** [comment]
https://medium.com/luxor/mining-pool-payment-methods-pps-vs-pplns-ac699f44149f

**Comment by MaynardMiner** [comment]
https://github.com/MaynardMiner/SWARM/issues/89

I didn't realize these were the same pools (same owners).

This is in the pipeline of things to do. I will look into their other pool (ethash) as well.
