### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#16]
.Net core 3.0 (currently experimental) contains system.windows.winforms

This means that powershell core, when developers finish porting .net 3.0 sdk to Powershell, will likely be capable of having a GUI in linux. I have researched many different forms of GUI, but a native Powershell/.Net GUI would make maintaining the project ideal, as it can be directly integrated.

I am currently designing a GUI for SWARM as we speak, in preparation of this, however, I do not know when they will finish Powershell 6.3, plus how much of the codebase will have to change to support 6.3, as well as how much of the GUI I am designing now will have to be ported/fixed when it is released.

**Comment by MaynardMiner** [comment]
My ideal situation is the GUI to be optional, for those running lighter distributions, and the GUI will mainly server as an easier way to modify the files in the config directory, along with changing arguments.

**Comment by MaynardMiner** [comment]
I am working on a gui on the ``alpha_testing`` branch. It is highly experimental, and nowhere near completed.

It is using the new Avalonia, with a modified ``PSAvalonia`` module that I made, that allows the implementation of reactiveUI. There are still bugs in Avalonia, as it is a new program, but so far it has been working fairly well.

Details for both are here:

https://github.com/MaynardMiner/psavalonia
https://github.com/AvaloniaUI/Avalonia

**Comment by arminmacx** [comment]
just the idea, I think if you could make web-based management for SWARM it will be better. everyone could forward their IP and see it anywhere without any specific software and manage their miner

**Comment by MaynardMiner** [comment]
I actually have a solution to both.

Avalonia will allow me to write a GUI in XAML framework that works on all OS's. It is not hard to convert XAML to HTML, and make an online version of the GUI.

I am re-developing SWARM now to have a much broader scope than just profit switching. My personal goal is to make a framework for mining administration written in Windows powershell, much like the ones currently written in Linux bash script.

From there, I will have a lot more options available, and a broader framework to work upon. I can't promise that I would work on/start a monitoring site, but it is an option that would be explored.

**Comment by MaynardMiner** [comment]
Just an update-

I am working on v2, which is going to be a total rewrite of SWARM, because I have added/butchered the codebase over time to which even I have a hard time finding/adding new code. A lot of it has been to slip in user ideas and workaround issues with powershell as it was being developed for linux...As well as adapt to the every changing crypto atmosphere.

Now that I have a pretty minimal-issue program, I am going to rewrite as cleanly as I can for both myself and other developers that may be interested. I also really want to get a CLEAN way to add the ability to create and manage rental services (mining rig rentals).

My goal is to create a fairly in depth http API that can be called on remotely while writing v2. There is an HTTP API already for SWARM, but it's limited in scope. I plan to attempt to expand upon it.

From there I will try to make the API the basis for both a web-app and/or GUI of some form.

**Comment by itsdarklikehell** [comment]
I am very interested, and willing to help where I can. (Scout's honor)
