### ISSUE TITLE
tpruvot-1 failed to download??? cuda 9.2

### ISSUE THREAD

**Issue by sharazhd** [MaynardMiner/SWARM#18]
DIR:SWARM/config/update/nvidia9.2-linux.json 
If you change from:
"tpruvot": {
.... 
"uri":"https://github.com/MaynardMiner/MM.Compiled-Miners/releases/download/v4.0/tpruvot-Linux-9-2.tar.gz"
...
},
To:
"uri":"https://github.com/MaynardMiner/MM.Compiled-Miners/releases/download/v4.0/tpruvot-linux-9-2.tar.gz"

then the problem is solved when linux sees the difference in large L and slightly l

**Comment by MaynardMiner** [comment]
Fixed the update link.

btw, you can run -Cuda 10 and get the latest miners, instead of using old ones. You just need to make sure you are running closer to recent drivers.
