### ISSUE TITLE
Possible Removal of /hive/bin and/or /hive/sbin.  HiveOS beta image (possible libcurl3 issue).

### ISSUE THREAD

**Issue by 0398955** [MaynardMiner/SWARM#195]
you fucker fucker! with your latest version I killed rigs! HiveOS. I fucked your mouth. So your hands are dry and your eyes come out. Stupid fool!
the folders / hive / bin / and / hive / sbin / were destroyed

**Comment by incodemines** [comment]
This was such an insightful and constructive comment. Perhaps you could share with us your actual problem, if there's even one to report, rather than just trolling. You either have no idea what you're doing or you're just bored.

**Comment by 0398955** [comment]
I clearly described the problem

the folders / hive / bin / and / hive / sbin / were destroyed

**Comment by 0398955** [comment]
the folders / hive / bin / and / hive / sbin / were destroyed

**Comment by incodemines** [comment]
That's not relative to SWARM. SWARM installs in the /hive/miners/custom/ folder. I've been using SWARM for over a year, nearly every version Maynard has ever released and I've never experienced anything like what you're describing. There is an entire Discord server full of us using SWARM.

**Comment by 0398955** [comment]
I wrote what happened to me. and this is not the first time. the dumbest program !!!!

**Comment by incodemines** [comment]
You've either done something within HiveOS to corrupt the main system files or changes made by HiveOS has caused your problem.

**Comment by incodemines** [comment]
I run two variants of SWARM over three rigs with both GTX and RTX cards on HiveOS and Windows 10. I know others who have hundreds and some thousands of GPUs who haven't experienced what you're stating. Regardless, you're acting as if your rig just went up in flames when all you need to do is reinstall HiveOS.

**Comment by incodemines** [comment]
If you want help you're going to have to give some kind of explanation of what you did to have the problem occur. I'm not saying your problem didn't occur but just coming here to shit talk and offer no substance to why you think SWARM is responsible is childish.

**Comment by 0398955** [comment]
Буду писать по русски. Если нет переводчика, то это твоя пооблема.
После начала установки риг сразу пропал в вэб хайва. Хотя через hiveshell доступ оставался. После перезагрузки., риг не загрузился.

**Comment by incodemines** [comment]
https://discord.gg/GDvqtv There is a channel specific to Russian speakers. Maybe somebody there can help troubleshoot the issue with you. SWARM makes no changes outside of the /hive/miners/custom/SWARM.x.x.x/ folder. Somewhere during the install process you've done something wrong. SWARM installs using a flight sheet via HiveOS. It's no different than if you were using HiveOS without SWARM.

**Comment by 0398955** [comment]
if you want I will shoot a video, I will demonstrate how this error works.  if you pay me 0.005 BTC.  And I will prove that SWARM is to blame for the error of my rigs.  This is the end of the conversation.  I expressed my opinion and warned other miners.

**Comment by MaynardMiner** [comment]
@0398955 

Спасибо за сообщение об ошибке. У меня есть сотни пользователей, некоторые из них работают на крупных фермах, и никто не сообщил о такой проблеме. Тем не менее, я буду расследовать это немедленно.

SWARM использует команды usr / bin, а не / hive / bin или / hive / sbin. Я не вижу ссылки на кодовую базу, в которой есть доступ к / hive / bin или / hive / sbin, кроме команд `` gpu-stats``.

Могу ли я спросить, какую версию HiveOS вы использовали, когда возникла эта проблема, чтобы я мог попытаться воспроизвести и немедленно устранить ее? Прямо сейчас на новом HiveOS я не могу воспроизвести вашу ошибку.

**Comment by 0398955** [comment]
System type
linux
Kernel
5.0.21-hiveos

**Comment by MaynardMiner** [comment]
Все буровые установки, на которых я сейчас тестирую, это 4.13.16-hiveos. Я попробую 5.0.21-hiveos и посмотрю, какие проблемы возникают.

**Comment by 0398955** [comment]
"Все буровые установки, на которых я сейчас тестирую, это 4.13.16-hiveos. Я попробую 5.0.21-hiveos и посмотрю, какие проблемы возникают."

**Comment by 0398955** [comment]
as your friend https://github.com/incodemines ... said ... that nothing bad happened .... but I had to go 200 km. to reinstall the highway in the rigs.

**Comment by MaynardMiner** [comment]
5.0.21-hiveos - это 18.04 Ubuntu. Во многих местах написано, что SWARM отлично работает в 16.04, и поддержка бета-изображений HiveOS ограничена.

Однако я чувствую, что знаю, в чем проблема - у меня были зависимости libcurl, которые вызывали проблемы с HiveOS и SWARM в прошлом (около 6 месяцев назад). На самом деле это не ошибка в HiveOS или SWARM, это проблема совместимости Libcurl3 в 18.04, но это требуется многим майнерам. Это вызовет эту проблему. Я исправил один раз, но HiveOS может что-то изменить, и сломает мое исправление. Трудно следить за изменениями бета-изображения. Если они снова прервали экспорт SWARM libcurl3, я исправлю это как можно скорее.

**Comment by 0398955** [comment]
So I was right?

**Comment by 0398955** [comment]
Of course, I apologize for the rude words. but you understand me ... when you start your program, lose all rigs.

**Comment by MaynardMiner** [comment]
Если libcurl3 не экспортируется должным образом, это сломает изображение. Вот как это деликатно. Я прошу прощения, что пропустил тот факт, что они изменили его, если он это сделал, я не слежу за бета-разработкой (бета-изображение). Я обращаю внимание на основное изображение.

 Я подключусь к бета-образу, посмотрю, если это проблема, и исправлю как можно скорее, если это так. Я сейчас не перед компьютерами, чтобы проверить, но это было проблемой раньше.

**Comment by 0398955** [comment]
"""Однако я чувствую, что знаю, в чем проблема - у меня были зависимости libcurl, которые вызывали проблемы с HiveOS и SWARM в прошлом (около 6 месяцев назад). """

and I wrote about this in discord

**Comment by MaynardMiner** [comment]
I don't remember seeing it in discord, but this is a reoccurring issue. that occasionally appears whenever they overhaul their beta image that I have to deal with. I will see if I'm right tonight, and find fix if this is the case.

Libcurl3 is required for older miners. However, libcurl3 was never written for 18.04 Ubuntu..So its very tricky to get it to work, to the point that if one thing changes- It will break the 18.04 kernel if one thing changes. This is not technically a SWARM issue, but an issue with linux overall that both HiveOS and SWARM have to find ways to work around it.

However, if you use 16.04 (regular image), you will not experience any issues with current release.

**Comment by 0398955** [comment]
I ask for forgiveness, but for myself I made a choice ....
Your program is dangerous for HiveOS. and pass this on to your friend https://github.com/incodemines who assured me that I was wrong.

**Comment by MaynardMiner** [comment]
Its not dangerous for hiveos, but is dangerous for hiveoa beta.

That is why it is their beta. I break their beta image all the time for my vegas, doing thinga not related to SWARM. Just run ``apt-get install`` anything on that image can potentially break their kernel.

Its not their fault. Ita the lack of compatibility between 16.04 and 18.04 Ubuntu.

**Comment by 0398955** [comment]
it is not their fault (hiveos). it's your fault because you cannot adapt your program to new hiveos images

**Comment by incodemines** [comment]
The program works great when you're not using the beta version of HiveOS. This is mining -- you want stability -- just use the stable image and it works as it's intended to. I never considered that you were using the HiveOS beta and you never said it in any of your original comments. You came here attacking a developer who literally supplies you with free and open source software that's unique to mining and attack him because your reluctance to use the stable image of HiveOS.

You should be grateful that this software exists, there are people here to help you at no cost, and the problem is being fixed. Instead you continue to be disrespectful.

**Comment by 0398955** [comment]
oh you bitch !!!!! the description of this software does not indicate that it is not compatible with the new kernel.

**Comment by 0398955** [comment]
https://github.com/incodemines  mother's son

**Comment by MaynardMiner** [comment]
I understand why you be upset, and you have my apologies, but I am only 1 guy trying to develop software that works in multiple OS's, and this software is free-to-distribute/open source- I make almost nothing in developing it besides using it for myself. There is a feature that adds donation, that most people remove.

There is a reason why nobody else has profit switching software that works directly on HiveOS along with supporting Windows- it isn't easy to do. Feel free to make something for yourself, and I will be more than happy to support/assist you.

I thank you for the report/review, and I am loading a bleeding-edge image now to find cause and fix.

**Comment by MaynardMiner** [comment]
Initially installing hiveOS beta image, SWARM is working fine. I am going to benchmark through all miners, to see if there is a miner that is cause. So far though, don't know where you are having the issue.

My steps:

-Copied hiveos bleeding edge image with etcherio
-Entered userid & password to connect to rig.
-Cloned current master branch (no different than release)
``cd /hive/miners/custom``
``git clone https://github.com/MaynardMiner/SWARM.git``

-Started my flightsheet (without link, custom miner name SWARM)

![2019-10-19-190912_1440x900_scrot](https://user-images.githubusercontent.com/38481606/67152447-7bf93a00-f2a4-11e9-8b5d-bf486d6a740e.png)
![2019-10-19-191144_1440x900_scrot](https://user-images.githubusercontent.com/38481606/67152448-7bf93a00-f2a4-11e9-8a77-1039645440fc.png)
![2019-10-19-191158_1440x900_scrot](https://user-images.githubusercontent.com/38481606/67152449-7bf93a00-f2a4-11e9-855f-baa268e5ab4b.png)

**Comment by MaynardMiner** [comment]
Once it benchmarks through, I will use the current release link just to make sure there isn't anything different than running it through master branch directly and git. But right now the codebase is no different on master branch than current release.

**Comment by MaynardMiner** [comment]
I have also stopped miner multiple times & restarted, restarted computer, and ran through all commands. I cannot reproduce as of yet, but it takes awhile to benchmark through all miners...It could be a miner that is cause, I am still investigating. Just relaying my findings thus far.

I still need to test AMD side, but AMD does nothing different besides run a command to get opencl platform.

**Comment by MaynardMiner** [comment]
Not a single problem in beta image.

This must be hardware issue, lack of ram with no swap, or failing drive. I have other users testing, and have no issues either. I am closing.

There is nothing SWARM does that could even remove /hive/bin or sbin- No mention of them in codebase, and Hiveos has changed nothing with libcurl dependencies.

Swarm is fine to use in bleeding edge with latest image. I am using it right now in all my rigs atm.
