### ISSUE TITLE
AMD stability

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#2]
SWARM does not have a lot of AMD users.

Be advised when using SWARM for AMD, you are beta testing AMD side- Please report in Discord in README of issues, or post issues in issues sections so I can quickly determine issues.

**Comment by HiddeHoogland** [comment]
I Will :)

**Comment by MaynardMiner** [comment]
Feedback has been miners currently in SWARM unix files are stable.

I am closing for now.
