### ISSUE TITLE
Lyra2z330 for Cuda

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#214]
I am looking for a Lyra2z330 for Cuda, preferably a working ccminer that I can overhaul/update.

I have tested a few with the kernel added, but they were all crashing when updated/compiled.

**Comment by Minerx117** [comment]
https://github.com/Minerx117/ccminer8.21r9-lyra2z330 tried this one?

compiles fine on windows not tested linux yet..

**Comment by MaynardMiner** [comment]
No. I just saw it.

I will check it out.

Thanks @Minerx117. You're the guy. ;)

**Comment by Minerx117** [comment]
no worrys, your welcome, hope it was of help to you
Best Regards
Nemo

**Comment by MaynardMiner** [comment]
Line 158 in Lyra2z330.cu & line 62 in Lyra2v2.cu

```
	return  scanhash_lyra2_base(thr_id, pdata, ptarget, max_nonce, hashes_done, 2, 330, 256, FALSE);
```

and

```
	LYRA2(hashB, 32, hashA, 32, hashA, 32, 1, 4, 4, FALSE);
```

I had to change to:

```
	return  scanhash_lyra2_base(thr_id, pdata, ptarget, max_nonce, hashes_done, 2, 330, 256,(uint32_t)0);

	LYRA2(hashB, 32, hashA, 32, hashA, 32, 1, 4, 4, (uint32_t)0);
```

FALSE is in minwindef.h according to visual studio intellisense, which is not linux.

After adding instructions to makefile, and making that fix. It compiles/works in linux.

**Comment by Minerx117** [comment]
i have made some changes to source code regarding intensity and compute compatibility
+0.2-2% hashrate on 10series cards
+12-22% hashrate on RTX/1660ti cards

recommend -i 12.5 for best results 
and a high memory OC +500-750mhz seems optimal
