### ISSUE TITLE
HiveOS 0.6-104@191219 update problem

### ISSUE THREAD

**Issue by vvpospelo** [MaynardMiner/SWARM#259]
Unable to install miner from https://github.com/MaynardMiner/SWARM/releases/download/v2.8.6/SWARM.2.8.6.linux.tar.gz

**Comment by vvpospelo** [comment]
Config : 
-Poolname nicehash,zergpool,zpool -Donate .5 -Location EUROPE -API_Key XXXXX -Type NVIDIA1 -kwh 0.0519 -WattOMeter Yes -Wallet1 %WAL% -Nicehash_Wallet1 3QoYusiipwREqwe3WY4HFB2oUPYPv6nve1 -PasswordCurrency1 BTC -RigName1 %WORKER_NAME% -Currency USD -CoinExchange BTC -Historical_Bias 33 -Switch_Threshold 3 -Nicehash_Fee 2 -Stat_Algo Hour_4 -Stat_Coin Hour_4 -Update Yes -Benchmark 240 -Interval 300 -StatsInterval 1 -Time_Wait 10 -SWARM_Mode No -Conserve Yes -Rejections 66 -Timeout 24 -Bans beamv2:bminer-1,cuckaroo29d:nbminer-1,mtp:tt-miner-1,mtp:cryptodredge-1,progpow:tt-miner-1,cuckarood,grincuckaroo29,yescryptr8g

**Comment by vvpospelo** [comment]
Config :
-Poolname nicehash,zergpool,zpool -Donate .5 -Location EUROPE -API_Key XXXXX -Type NVIDIA1 -kwh 0.0519 -WattOMeter Yes -Wallet1 %WAL% -Nicehash_Wallet1 XXXXXX -PasswordCurrency1 BTC -RigName1 %WORKER_NAME% -Currency USD -CoinExchange BTC -Historical_Bias 33 -Switch_Threshold 3 -Nicehash_Fee 2 -Stat_Algo Hour_4 -Stat_Coin Hour_4 -Update Yes -Benchmark 240 -Interval 300 -StatsInterval 1 -Time_Wait 10 -SWARM_Mode No -Conserve Yes -Rejections 66 -Timeout 24 -Bans beamv2:bminer-1,cuckaroo29d:nbminer-1,mtp:tt-miner-1,mtp:cryptodredge-1,progpow:tt-miner-1,cuckarood,grincuckaroo29,yescryptr8g

**Comment by MaynardMiner** [comment]
I posted on release.

There was an issue with packaging.

Try it now, it should be fixed.

I accidentally tar.gz it in a folder in a folder.
