### ISSUE TITLE
My AMD cards are not mining

### ISSUE THREAD

**Issue by wallacepf** [MaynardMiner/SWARM#353]
Hello guys,

I have a rig with AMD+NVIDIA cards (1x 1070 + 5 x 5500 XT). For some reason it's not mining with my AMD cards and I got the following error:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/4224243/109408101-11aadc00-7965-11eb-97d7-2c077e16ae1e.png">

Checking the logs, I got the following:

```
/hive/miners/custom/SWARM.3.5.7.linux/bin/gminer-amd-1# /hive/miners/custom/SWARM.3.5.7.linux/bin/gminer-amd-1/miner -d 5 0 3 1 4 -
-api 33001 --server cuckoocycle.usa.nicehash.com --port 3376 --algo aeternity --user 35fSRbY1XAp6uTFTPoosiT4f2vTLYNNLCv.SWARM --pass x --logfil
e '/hive/miners/custom/SWARM.3.5.7.linux/logs/AMD1.log'
invalid device index: 5
```

**Comment by MaynardMiner** [comment]
-d 5 0 3 1 4

It's detecting devices as 0 1 3 4 5. It's skipping 2 for some reason? I think this is the cause. Is there another gpu on the board?

**Comment by henrysia998** [comment]
![IMG_20210613_022022.jpg](https://user-images.githubusercontent.com/83953811/121783531-4da13e80-cbee-11eb-9473-7fba9aa26b60.jpg)

Mee to see pic
