### ISSUE TITLE
Ethereum with HiveOS on windows ?

### ISSUE THREAD

**Issue by chmichael** [MaynardMiner/SWARM#354]
Hello,
  Is ethereum mining with HiveOS/Pool supported ? I only see BTC.

Thank you

**Comment by MaynardMiner** [comment]
Hello I'm sorry I didn't respond- I didn't even see the issues.

HiveOS is used, but not HiveON pool. SWARM is meant to work with only pools that offer some form of auto-exchange or auto-switching.
