### ISSUE TITLE
Import pools from HiveOS

### ISSUE THREAD

**Issue by Speeddymon** [MaynardMiner/SWARM#368]
I am wanting to start mining ethereum with poolin.me pool but it seems to only be an option if I don't use a custom miner like swarm, so I wanted to ask if it would be possible to import the pool settings from HiveOS into swarm so that those pools can be tested benchmarking and used during mining if they are the most profitable.

**Comment by incodemines** [comment]
Maynard has been on a break for the past few months focusing more on his main business. That said, I'm also interested in trying to add some extra pools into SWARM. I'm using my own fork in which I've updated nvidia windows miners. I'm mostly mining on Nicehash but I'm desperately needing an ETH pool inside SWARM. Whalesburg is in the process of returning but it's been a long six months or so getting there. If I'm able to figure out how to get more pools in, I'll report back.

**Comment by Speeddymon** [comment]
Thanks! I've been poking around because I noticed there have been a few commits since the last release and I wanted to update miners as well. I'll see if I can find anything as well

**Comment by MaynardMiner** [comment]
There is not way to auto-add pools- It is impossible to auto-detect necessary settings needed to do so for each algo-miner combination.

I can look into it if I decide to revitalize the project, because it does look like it's a PPS pool, which is good for switching.
