### ISSUE TITLE
Version 3.6.5 has xmrig-cpu outdated version, causing miner hang up

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#396]
Version 3.6.5 has an outdated version of xmrig-cpu installed, which causes miner to crash with a "Read File Error"...

xmrig-cpu    cpu  xmrig         **6.7.0**
xmrig-a        amd  xmrig          6.18.0
xmrig-n      nvidia xmrig         6.18.0

Fixed isue with manual update command, resulting in the below : 
version update xmrig-cpu 6.18.0 https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-static-x64.tar.gz

**xmrig-cpu    cpu  xmrig         6.18.0**
xmrig-a        amd  xmrig          6.18.0
xmrig-n      nvidia xmrig         6.18.0

**Comment by MaynardMiner** [comment]
https://github.com/MaynardMiner/SWARM/issues/408

Closing because I am fixing here
