### ISSUE TITLE
Custom parameters in AMD miner json file, dont get passed to SWARM

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#413]
Issue only with AMD. See NVIDIA arguments getting passed properly in last image... (--gpu-temp-limit 61 --gpu-temp-resume 55)

![image](https://user-images.githubusercontent.com/99490445/197394787-8493099e-84e0-480e-9e1f-4378f6f16622.png)

![image](https://user-images.githubusercontent.com/99490445/197394864-7d614c2c-3350-4441-96ad-1b6fb185e1cb.png)

![image](https://user-images.githubusercontent.com/99490445/197394904-925d170f-5a3d-417e-8439-0778d3f875d5.png)

**Comment by MaynardMiner** [comment]
Can you try this for me?

At this line:

https://github.com/MaynardMiner/SWARM/blob/master/miners/gpu/amd/wildrig.ps1#L84

At the end change change:

```
 $($MinerConfig.$ConfigType.commands.$($MinerConfig.$ConfigType.naming.$($_.Algorithm)))
```
To
```
$($MinerConfig.$ConfigType.commands.$($_.Algorithm))
```
And see if it fixes it.

**Comment by UserDC-LeGrand** [comment]
![image](https://user-images.githubusercontent.com/99490445/197657480-182c0bc4-7a66-4c09-b777-f0481b58d008.png)

![image](https://user-images.githubusercontent.com/99490445/197657634-754c5058-cd2a-4528-af60-1b51df026ed1.png)

![image](https://user-images.githubusercontent.com/99490445/197657389-33dee5d2-02a2-42f5-a4fa-c269332081d9.png)

**Comment by UserDC-LeGrand** [comment]
Reverted to originalscript, and I must have done something wrong at the time, prior to 3.6.6, as it now works ...

![image](https://user-images.githubusercontent.com/99490445/197658563-572fbefd-8d89-46f4-84a0-1450662d9205.png)
