### ISSUE TITLE
Issue with upgrade command

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#414]
Probably related to miniz Download site....

Upgrade never completes, and hangs there without ever a prompt coming back...

**EDIT:**
Issue resolved by wrapping the URI in single quotes such as:
version update miniz v1.9z4 'https://miniz.ch/?smd_process_download=1&download_id=4762'

instead of the failing :
version update miniz v1.9z4 https://miniz.ch/?smd_process_download=1&download_id=4762

![image](https://user-images.githubusercontent.com/99490445/197395094-8aceb9ec-b081-4ed1-8a46-9f7f7d376631.png)

There seems to be an issue with the download link, but download works on local Win desktop...

![image](https://user-images.githubusercontent.com/99490445/197421213-9bd5850e-599b-4e28-8056-c721b35d60f5.png)

**Comment by UserDC-LeGrand** [comment]
Issue resolved by adding single quotes to wrap the URI ...

![image](https://user-images.githubusercontent.com/99490445/197514588-16b7e873-8ce3-4816-9248-5c9a0f56b2db.png)

**Comment by MaynardMiner** [comment]
https://github.com/MaynardMiner/SWARM/wiki/Commands-&-Suggested-Apps



"To give an example:

version update z-enemy 1.20 "https://github.com/MaynardMiner/MM.Compiled-Miners/releases/download/v4.0/z-enemy-Linux9-1.tar.gz"

Rules for updating miner:

-Compression must be tar.gz for linux, or .zip in windows.

-Place link between quotes to avoid command-line issues."
