### ISSUE TITLE
bans remove command does not allways provide feedback ...

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#415]
Refer to last three bans remove commands in the image. Specific algo:miner command failed, but global algo bans worked ...

![image](https://user-images.githubusercontent.com/99490445/197397525-1f579667-1bc0-4df3-a2b1-1b3d44703940.png)

**Comment by MaynardMiner** [comment]
So this is kind of tricky situation.

The ``bans`` command was meant to be a command to add/remove bans as you would the ``-bans`` argument. I added it so I didn't have to edit my flight sheet every time I wanted to ban something.

The bans happening here- Are not actually defined "Bans", but what in the code I refer to as "timeouts". They are rules generated by SWARM and not the user, and they are more specific than what the user can ban: Users are limited to algo:miner or algo:pool, etc...But these are technically algo:miner:pool. There is also an argument related to timeouts and how often you want them cleared.

Currently the only way to remove them, is ``bench bans`` which clears the SWARM generated rules (It just deletes the saved timeout files)

You are kind of working in reverse- You should be adding the bans you want permanent to your ``-bans`` argument, and then ``bench bans`` the rest.

**Comment by MaynardMiner** [comment]
I'll look at the code, and see if I can do better, including it ALWAYS having it return some kind of output.

**Comment by UserDC-LeGrand** [comment]
As Im working though the root cause for SWARM initiated bans, mostly due to miner crashes, agressive tuning in miner config files, wrong OC's, etc -  I use the specific bans command and bench to force a new benchmark for the algo:miner combo, and I screen -r NVIDIA1 or AMD1 to see in real-time what is causing the issue. Eventually, the individual miner logfiles you will be anbling soon will help troubleshotting past events ....

**Comment by MaynardMiner** [comment]
Will be fixed in #418
