### ISSUE TITLE
Support for miniz on AMD  GPU's

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#417]
The only config file present is for NVIDIA.

Perhaps this exclusion is warranted, as miniz is not listed on the AMD version query list ...

![image](https://user-images.githubusercontent.com/99490445/197416741-5182195f-5960-45a3-aa13-e04702d44199.png)

![image](https://user-images.githubusercontent.com/99490445/197416844-dda52155-cbd2-4516-89fd-b22b6040f01a.png)

![image](https://user-images.githubusercontent.com/99490445/197416965-e7451e9b-8a5e-47a5-86df-2d3b28c5b851.png)

**Comment by MaynardMiner** [comment]
I don't have an AMD version up for mini-z yet. I need to make two separate configs- One miniz-a.json and one miniz-n.json.

I will get it in. I just haven't had time to test it on my AMD rig yet and go through all the settings to see what arguments are needed/changed for AMD side.
