### ISSUE TITLE
Hash rates wrongly associated on HiveOS dashboard

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#419]
This issue is strange.

On Gminer-N ETHASH, somehow the hash rates for the 3070 GPU#2, wind up in GPU#0.
The first two 2060 GPU's (0 an1) should hover around the 30-32 Mh/s range, and the last 3070 GPU around the 60-63 MH/s range. 

The issue is in the way you build your scripts ... Look at the order of the devices you are passing on the command line - -d 6 7 4 2 0 3 5 1 . This should be removed or properly sequence such as this**: 0 1 2 3 4 5 6 7**

root@rig4:/hive/miners/custom/SWARM.3.6.7.linux/bin/gminer-a-1# /hive/miners/custom/SWARM.3.6.7.linux/bin/gminer-a-1/miner -d 6 7 4 2 0 3 5 1 --api 33001 --server etchash.auto.nicehash.com --port 9200 --algo etchash --proto stratum --user xxxxxxxxxxxxxxxxxxxxxxx.rig4 --logfile '/hive/miners/custom/SWARM.3.6.7.linux/logs/gminer-a-1.log' --pass x --templimit 61

![image](https://user-images.githubusercontent.com/99490445/197659574-4512fe7d-5050-4bfd-a487-8f5ee027fad8.png)

![image](https://user-images.githubusercontent.com/99490445/197659622-5e092d85-18e2-4bb6-8c5a-1fec8683688f.png)

**Comment by MaynardMiner** [comment]
Go to .\debug\busdata.txt

Please confirm that it is sorting the gpus correctly by busid.

If that is correct, check ``agent-screen`` and see if ``bus_numbers`` are correct.

If that is correct, check order of hashrate presented in ``agent-screen``. If it's showing the 64.61 mh/s as first, then this is issue with Gminer, not SWARM.

**Comment by MaynardMiner** [comment]
Follow up- Did you ever check? I was searching code, and I don't see how Swarm atm could display hashrates in wrong slot currently (not to say bug isn't there).

Most miners don't show what hashrate goes to which gpu, just a list of hashrates in api. It is assumed it is displayed in order of gpu bus.

**Comment by UserDC-LeGrand** [comment]
I did but the sequence was OK for the miner/algo combo at the time I checked. I need ot do this again – and benchmark that specific miner/algo combo, while stairng at the background screens and pointers you mentioned. You are probably bang on with the specific miner having the issue ...

**Comment by UserDC-LeGrand** [comment]
Gminer or is it HiveOS:  displaying the hashrates out of sequence on another rig this morning ...

The 63.5 MH/S ... should be assigned to the 3070LHR GPU 0 and 2 ...

![image](https://user-images.githubusercontent.com/99490445/198839905-b3cf75d1-f940-4446-8e18-5535242d5c90.png)

![image](https://user-images.githubusercontent.com/99490445/198839972-d2404fa5-c909-48ba-be08-51fdcf9bd3ea.png)

**Comment by UserDC-LeGrand** [comment]
Found the issue, and perhaps it is in the way you build your scripts ... Look at the order of the devices you are passing on the command line :

root@rig4:/hive/miners/custom/SWARM.3.6.7.linux/bin/gminer-a-1# /hive/miners/custom/SWARM.3.6.7.linux/bin/gminer-a-1/miner -d 6 7 4 2 0 3 5 1 --api 33001 --server etchash.auto.nicehash.com --port 9200 --algo etchash --proto stratum --user xxxxxxxxxxxxxxxxxxxxxxx.rig4 --logfile '/hive/miners/custom/SWARM.3.6.7.linux/logs/gminer-a-1.log' --pass x --templimit 61

![image](https://user-images.githubusercontent.com/99490445/198840764-74103f58-1fa6-4164-bbbc-4d0f6c5fb5fb.png)

**Comment by MaynardMiner** [comment]
Are you using the ``-GPUDevices1`` argument?

**Comment by MaynardMiner** [comment]
Can you post your debug\devicelist.txt file here? I just want to know how SWARM is recording them.

**Comment by MaynardMiner** [comment]
.\debug\busdata.txt too. If you can post both files, I can figure out issue.

**Comment by UserDC-LeGrand** [comment]
Im not using -GPUdevicec1 or other...
I just use -Type NVIDIA1,CPU or AMD1,CPU argument depending on rig.

**Comment by UserDC-LeGrand** [comment]
As requested. The busid is correctly sequenced. The device list is not ...


root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug# cat busdata.txt 
[
  {
    "busid": "03:00.0",
    "name": "NVIDIA TU106 [GeForce RTX 2060 Rev. A]",
    "brand": "nvidia",
    "subvendor": "ASUS",
    "mem": "6144 MiB",
    "vbios": "90.06.46.00.89",
    "plim_min": "105.00 W",
    "plim_def": "190.00 W",
    "plim_max": "238.00 W"
  },
  {
    "busid": "06:00.0",
    "name": "NVIDIA TU106 [GeForce RTX 2060 Rev. A]",
    "brand": "nvidia",
    "subvendor": "ASUS",
    "mem": "6144 MiB",
    "vbios": "90.06.46.00.89",
    "plim_min": "105.00 W",
    "plim_def": "190.00 W",
    "plim_max": "238.00 W"
  },
  {
    "busid": "08:00.0",
    "name": "NVIDIA GA104 [GeForce RTX 3070 LHR]",
    "brand": "nvidia",
    "subvendor": "EVGA",
    "mem": "8192 MiB",
    "vbios": "94.04.46.40.60",
    "plim_min": "100.00 W",
    "plim_def": "240.00 W",
    "plim_max": "270.00 W"
  }
]
root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug# cat devicelist.txt 
{
  "AMD": {},
  "CPU": {
    "11": 11,
    "9": 9,
    "7": 7,
    "6": 6,
    "2": 2,
    "13": 13,
    "12": 12,
    "3": 3,
    "4": 4,
    "8": 8,
    "10": 10,
    "0": 0,
    "5": 5,
    "1": 1
  },
  "NVIDIA": {
    "2": "2",
    "0": "0",
    "1": "1"
  }
}
root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug#

**Comment by MaynardMiner** [comment]
> As requested. The busid is correctly sequenced. The device list is not ... Should it not be 0, 1 ,2 ?
> 
> root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug# cat busdata.txt [ { "busid": "03:00.0", "name": "NVIDIA TU106 [GeForce RTX 2060 Rev. A]", "brand": "nvidia", "subvendor": "ASUS", "mem": "6144 MiB", "vbios": "90.06.46.00.89", "plim_min": "105.00 W", "plim_def": "190.00 W", "plim_max": "238.00 W" }, { "busid": "06:00.0", "name": "NVIDIA TU106 [GeForce RTX 2060 Rev. A]", "brand": "nvidia", "subvendor": "ASUS", "mem": "6144 MiB", "vbios": "90.06.46.00.89", "plim_min": "105.00 W", "plim_def": "190.00 W", "plim_max": "238.00 W" }, { "busid": "08:00.0", "name": "NVIDIA GA104 [GeForce RTX 3070 LHR]", "brand": "nvidia", "subvendor": "EVGA", "mem": "8192 MiB", "vbios": "94.04.46.40.60", "plim_min": "100.00 W", "plim_def": "240.00 W", "plim_max": "270.00 W" } ] root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug# cat devicelist.txt { "AMD": {}, "CPU": { "11": 11, "9": 9, "7": 7, "6": 6, "2": 2, "13": 13, "12": 12, "3": 3, "4": 4, "8": 8, "10": 10, "0": 0, "5": 5, "1": 1 }, "NVIDIA": { "2": "2", "0": "0", "1": "1" } } root@rig5:/hive/miners/custom/SWARM.3.6.7.linux/debug#

This is not same rig.

Rig above has 9 gpus. This devicelist.txt shows only 3.

**Comment by MaynardMiner** [comment]
I think I found issue. It's being Powershell, and adding to the table out of order.

**Comment by MaynardMiner** [comment]
https://github.com/MaynardMiner/SWARM/commit/801bdb5b2bd8411a115045a73957646675f43b12

This should fix it, just I don't know the full extent/implications it will have particularly with cross-platform (AMD & NVIDIA) on rig. But it will order them by their device slot, and by extension the -d argument should be put correctly.

If you want to forward test and confirm while I'm working on other stuff, would appreciate it. It's a simple edit to the file notated in the commit.
