### ISSUE TITLE
Disconnect between current Pool and current Daily profit stats

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#420]
There is large gap between current Pool and current Daily profit stats. Running new benchmarks did not resolve the issue...

![image](https://user-images.githubusercontent.com/99490445/198051511-5110ce45-fe60-4756-9800-3526843c52c2.png)

**Comment by MaynardMiner** [comment]
``clear_profits``

The pool had a really high outlier stat that is affecting the average. It is why I display daily average to begin to show that.

You can Also use -Threshold argument to have Swarm try to prevent outlier stats like that when pool has issues.

https://github.com/MaynardMiner/SWARM/blob/master/help/SWARM_help.txt#L310
