### ISSUE TITLE
Update wiki documentation - Commands-&-Suggested-Apps

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#421]
Update documentation to reflect full list of arguments for **bench** command, as indicated in the SWARM miner console such as:

**bench miner srbmulti-a-1 yescryptr16**

and not just ...

bench algorithm [algorithm] or  bench miner [miner] 

 https://github.com/MaynardMiner/SWARM/wiki/Commands-&-Suggested-Apps

![image](https://user-images.githubusercontent.com/99490445/198276052-c27287f2-0075-42c5-90cd-5be95c56276b.png)

![image](https://user-images.githubusercontent.com/99490445/198275133-773eec2d-1263-4877-8097-5444c94d7c1f.png)

**Comment by MaynardMiner** [comment]
I will do.

**Comment by MaynardMiner** [comment]
I will do. Thank you for being so thorough.

**Comment by UserDC-LeGrand** [comment]
No issues. Just trying to help enhance your amazing creation in my tiny own way. If it can help others ... Im in ...
