### ISSUE TITLE
Update Miners

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#424]
Gminer
https://github.com/develsoftware/GMinerRelease/releases/tag/3.11

NanoMiner v3.7.4
https://github.com/nanopool/nanominer/releases/tag/v3.7.4

**Comment by MaynardMiner** [comment]
miniZ v1.9z4
https://miniz.ch/2022/10/22/miniz-v19z4-is-out

XMRig v6.18.1
https://github.com/xmrig/xmrig/releases/tag/v6.18.1

CPUminer-Opt-JayDDee v3.20.3
https://github.com/JayDDee/cpuminer-opt/releases/tag/v3.20.3

**Comment by UserDC-LeGrand** [comment]
https://github.com/andru-kun/wildrig-multi/releases/tag/0.33.4
