### ISSUE TITLE
Update miners within 3.6.7

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#426]
NVIDIA miner updates required:

wildrig-n 0.33.6 'https://github.com/andru-kun/wildrig-multi/releases/download/0.33.6/wildrig-multi-linux-0.33.6.tar.xz'
lolminer-n 1.61 'https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.61/lolMiner_v1.61_Lin64.tar.gz'
t-rex 0.26.8 'https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz'
gminer-n 3.12 'https://github.com/develsoftware/GMinerRelease/releases/download/3.12/gminer_3_12_linux64.tar.xz'
miniz-n v1.9z5b 'https://miniz.ch/?smd_process_download=1&download_id=4783'

AMD miner updates required:
wildrig-a 0.33.6 'https://github.com/andru-kun/wildrig-multi/releases/download/0.33.6/wildrig-multi-linux-0.33.6.tar.xz'
srbmulti-a 1.1.1 'https://github.com/doktor83/SRBMiner-Multi/releases/download/1.1.1/SRBMiner-Multi-1-1-1-Linux.tar.xz'
nbminer-amd 42.3 https://github.com/NebuTech/NBMiner/releases/download/v42.3/NBMiner_42.3_Linux.tgz
lolminer-a 1.61 https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.61/lolMiner_v1.61_Lin64.tar.gz
gminer-a 3.12 'https://github.com/develsoftware/GMinerRelease/releases/download/3.12/gminer_3_12_linux64.tar.xz'

**Comment by MaynardMiner** [comment]
Wow I missed all those?

I am following too many miner repos it's hard to keep up anymore. Thank you, I will hotfix an update over weekend.

**Comment by UserDC-LeGrand** [comment]
No issues – I manually updated all of these.

**Comment by UserDC-LeGrand** [comment]
wildrig-a 0.33.4.1 'https://github.com/andru-kun/wildrig-multi/releases/download/0.33.4.1/wildrig-multi-linux-0.33.4.1.tar.xz'

**Comment by UserDC-LeGrand** [comment]
srbmulti-a 1.1.1 'https://github.com/doktor83/SRBMiner-Multi/releases/download/1.1.1/SRBMiner-Multi-1-1-1-Linux.tar.xz'

**Comment by UserDC-LeGrand** [comment]
miniz-n v1.9z5b 'https://miniz.ch/?smd_process_download=1&download_id=4783'
