### ISSUE TITLE
Jayddee & Xmrig-n

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#427]
The release at the time it was posted had a incorrectly packaged file for new jayddee cpu miner. This has been resolved.

I am notating it here in case someone downloaded release before I had the ability to notice and fixed. The download link should work now.

**Comment by UserDC-LeGrand** [comment]
Confirmed! Works now.

**Comment by MaynardMiner** [comment]
The same issue occurred with xmrig-n

It was packaged in the same method as jayddee. I will no longer be using that method.
