### ISSUE TITLE
xmrig-n-1 download failed messages - mismatched miner names in scripts or other

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#429]
See below screen captures, where SWARM 3.6.7 is trying to download to xmrig-n-1, but should be to xmrig-n and xmrig-a instead . This occured when removing the timeout folder ...

![image](https://user-images.githubusercontent.com/99490445/198843731-872e919c-4382-47b1-8b85-58613f28da82.png)

![image](https://user-images.githubusercontent.com/99490445/198890859-cf62df79-7a0c-4aa3-b6f4-d013f463f277.png)

**Comment by MaynardMiner** [comment]
Package issue. Same as Jayddee #427
