### ISSUE TITLE
Add config\wallets\wallets.json

### ISSUE THREAD

**Issue by incodemines** [MaynardMiner/SWARM#43]
Rather than having an altwallet argument for only one altcoin payout for all pools allowing altcoin payouts instead doing an altwallet address and coin selection for each pool that allows it.

For example:
-altwalletzergpool1 <wallet address> -altcurrencyzergpool1 <altcoin symbol>
-altwalletzergpool2 <wallet address> -altcurrencyzergpool2 <altcoin symbol>
-altwalletzergpool3 <wallet address> -altcurrencyzergpool3 <altcoin symbol>
-altwalletnlpool1 <wallet address> -altcurrencynlpool1 <altcoin symbol>
-altwalletnlpool2 <wallet address> -altcurrencynlpool2 <altcoin symbol>
-altwalletnlpool3 <wallet address> -altcurrencynlpool3 <altcoin symbol>
-altwalletblockmasters1 <wallet address> -altcurrencyblockmasters1 <altcoin symbol>
-altwalletblockmasters2 <wallet address> -altcurrencyblockmasters2 <altcoin symbol>
-altwalletblockmasters3 <wallet address> -altcurrencyblockmasters3 <altcoin symbol>
-altwalletzpool1 <wallet address> -altcurrencyzpool1 <altcoin symbol>
-altwalletzpool2 <wallet address> -altcurrencyzpool2 <altcoin symbol>
-altwalletzpool3 <wallet address> -altcurrencyzpool3 <altcoin symbol>

By keeping the original -wallet argument for BTC payout for the pools that only allow BTC payout (ahashpool, blazepool, hash refinery) but allowing different altcoin payouts depending on pools. A reason for doing it this way is because some pools, like Zergpool, have altcoins that aren't available on other pools and in order to mine Zergpool for that altcoin I would either need to make a separate flight sheet and eliminate all other pools.

So this would allow me to mine for Zcoin payout on Zergpool, LTC payout on nlpool, RVN payout on zPool. It will take more time to set up arguments but it allows for users to finish off wallet balances to each pool's threshold and switch payouts. For instance, if I wanted to switch all my altcoin payouts from LTC to BTC, I could change the arguments for BTC payout after I reach a certain pool's threshold for LTC payout and still keep other pools in the rotation.

**Comment by MaynardMiner** [comment]
Thanks, will look into it soon.

**Comment by incodemines** [comment]
For users that would want to have BTC instead of an altcoin payout for say Zergpool they could just leave out the arguments -altwalletzergpool and -altcurrencyzergpool and Swarm could revert back to the -wallet (BTC) default wallet address. If they wanted to use a different BTC wallet they could use the two arguments and just specify it correctly.

**Comment by MaynardMiner** [comment]
I have decided that the optimal way to do this, is to make a configuration file for Wallets, that can be expanded up normal parameters.

I am trying to keep the arguments listing from being pages long, as well as keep a centralized configuration system.

I intend to create a configuration .json file, that will allow users to become very specific with the wallets they wish to use, as well as attempting to combining the idea for pool priority idea that was proposed.

This will also help a future idea of I have, of using explorers to tracking wallets post pool (block explorers).
