### ISSUE TITLE
Issue with wildrig-a.ps1 script in SWARM 3.6.7

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#430]
There seems to be an issue with this script: 

/hive/miners/custom/SWARM.3.6.7.linux/miners/gpu/amd/wildrig-a.ps1 

bench miner wildrig-a does not launch wildrig miner on AMD rig.

NVIDIA flavor works fine ...

![image](https://user-images.githubusercontent.com/99490445/198853394-e55a81ba-3f54-4c71-91b9-47ed1acf52b5.png)

**Comment by MaynardMiner** [comment]
It doesn't immediately launch miner...It needs to save the benchmarks/rejections of the miner previously, then returns to the start of the loop.

**Comment by MaynardMiner** [comment]
All miners must run for a minimum of 5 minutes in order to get an accurate benchmark of both rejections and hashrate
