### ISSUE TITLE
Create Device Specific Means To Specify Certain Algorithms.

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#431]
I want to be able to send specific Algo to GPU, and to CPU, with -Algorithm argument.
Both GPU and CPU default to same algo ...

![image](https://user-images.githubusercontent.com/99490445/198885874-f202d3bb-ed59-4364-aedb-afa65cfd990f.png)

![image](https://user-images.githubusercontent.com/99490445/198886053-c708b7e2-3b82-4893-bb60-b1fa8e945a52.png)

**Comment by MaynardMiner** [comment]
Is there a use case for this? Do we need arguments for each device type to have it's own set of algorithms?

**Comment by UserDC-LeGrand** [comment]
I would say it’s a must when mining CPU and GPU on same rigs. Case in point: I wanted to point my GPU’s at etchash and CPU at ghostrider, so I used the -Algorithm in my flightsheet. What SWARM ended doing is point both my GPU’s and CPU to ghostrider. This is why there should be both an Algorithm_GPU  and Algorithm_CPU argument to support this allocation to where you want it to go...

**Comment by UserDC-LeGrand** [comment]
just thought of something. I could try running two instances of SWARM. My fkightsheet would have a custom miner for the CPU, whether it is swarm or not, and one for the GPUs only,. Worst case, the Cpu miner I select, would not profit switch...

**Comment by MaynardMiner** [comment]
I don't know if that will work. I have never tried it. I will look into changing -Algorithm to -GPUAlgorithm and -CPUAlgorithm respectively if it is needed.

**Comment by MaynardMiner** [comment]
I made a fork from this issue.

On that fork I:

1.) Removed -Algorithm argument.
2.) Added -GPUAlgorithm1 argument.
3.) Added -GPUAlgorithm2 argument.
4.) Added -GPUAlgorithm3 argument.
5.) Added -CPUAlgorithm argument.

Obviously the -GPUAlgorithm argument corresponds to device group (NVIDIA1,NVIDIA2,NVIDIA3)

If you want to stress test it and report, please do.
