### ISSUE TITLE
bench all does not include all miners listed in bin folder

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#432]
On AMD Polaris rig, the  bench all command does not include teamredminer, which is listed in bin folder ...

![image](https://user-images.githubusercontent.com/99490445/198889774-52095f9b-05e2-4e18-9dc2-bb8d2b0cbb09.png)

![image](https://user-images.githubusercontent.com/99490445/198889815-fa7641a1-4226-4f11-ad30-147e162d6e94.png)

![image](https://user-images.githubusercontent.com/99490445/198889851-a2119800-6f4d-495e-bb02-42a69ec88e83.png)

**Comment by UserDC-LeGrand** [comment]
It appears to have added TeamRedMiner after the benchmarks ran for a  whitel, but only for small list of Algo's. Not sure why as TMR is one the most optimized miners for AMD Polaris GPU's ... 

![image](https://user-images.githubusercontent.com/99490445/198893964-c86cfc4d-dbaa-4987-945d-31c1c47f760c.png)

**Comment by UserDC-LeGrand** [comment]
Ran a bench miner teamredminer-1 once more, after the bench all, and now all Algos were benched like expected...

**Comment by MaynardMiner** [comment]
``get stats`` only shows 1 miner per algo. If there are other miners, it will appear after the miner listed benches.
