### ISSUE TITLE
 srbmulti-a.ps1 has wrong "--logfile" argument. Should be "--log-file"

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#434]
srbmulti-a.ps1 has wrong "--logfile" argument. Should be "--log-file"

![image](https://user-images.githubusercontent.com/99490445/198891711-928c242e-1264-42e8-ab19-dc0e7acd3f83.png)

**Comment by MaynardMiner** [comment]
will fix
