### ISSUE TITLE
add neoscrypt-xaya, sha512256d

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#435]
Find and add miners for the above algos.

**Comment by UserDC-LeGrand** [comment]
Please add support for megabtx as well ...

![image](https://user-images.githubusercontent.com/99490445/199199976-bb818579-3f47-41d8-97cd-35f8673096b6.png)

**Comment by MaynardMiner** [comment]
Do you have a miner to suggest? I'll look into one but finding one will expedite it.

**Comment by UserDC-LeGrand** [comment]
Last miner I ran successfully with sha512256d on both AMD and NVIDIA rigs was Wildrig 0.33.1
I imagine the latest 0.33.5 version would be good as well...

**Comment by UserDC-LeGrand** [comment]
Please note:  the pool-algos.json file in your repo, does not have an entry for sha512256d algo (Wildrig), nor sha512_256_radiant (SRBMulti naming convention)..

**Comment by MaynardMiner** [comment]
![image](https://user-images.githubusercontent.com/38481606/200625853-bd2ad51b-c26f-464d-96f9-d3af4e85c3b8.png)

It's there. You're probably not seeing it hit because nobody is finding blocks or something.

**Comment by MaynardMiner** [comment]
Also I missed sha256csm is done in wildrig, and is already added.

**Comment by MaynardMiner** [comment]
miners and algos were added....I added them to different fork instead of this issue. Closing
