### ISSUE TITLE
lolminer log file gets overwritten instead of appended

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#436]
lolminer-a-1.log file gets overwritten instead of appended, at every miner restart. This makes it impossible to troubleshoot previous incidents.

This can be resolved by using "tee" command with -a "append" argument ...
or using native miner --log and --logfile arguments ...

Other miners may have similar issue. This is T.B.D ....

![image](https://user-images.githubusercontent.com/99490445/200168300-1e1a6bc4-fd6f-4eed-9b0f-07a0173f41a0.png)

![image](https://user-images.githubusercontent.com/99490445/200169090-e07376a7-a59d-4cc3-8a53-bf43c23fc883.png)

**Comment by MaynardMiner** [comment]
Yeah I need to get a release out to get the new algos in. After that release I'm going to fix the logging to use shell-in-shell on windows and then stop using miner -log arguments.
