### ISSUE TITLE
CN pools support

### ISSUE THREAD

**Issue by davisinfo** [MaynardMiner/SWARM#44]
Support more CN algos / pools. 

Possible pools:
- miner.rocks - seems to be PPS like
  - API url based on algo, for example https://haven.miner.rocks/api/stats
  - seems to be based on NOMP by how API looks
- cryptoknight.cc
  - not sure if it is pool switching friendly
  - seems to have the same API format
  - https://cryptoknight.cc/rpc/haven/stats

**Comment by MaynardMiner** [comment]
Thanks, as I stated, will look into it.

My goal is to figure out their pool framework, and try to make 'generic' pool files for them, like I did with custom yiiimp pools, so you can add them / customize as you find more.

**Comment by MaynardMiner** [comment]
I am looking into adding monero ocean along with adding a -monero argument to add a monero wallet. This is in the pipeline of things to do.
