### ISSUE TITLE
AMD Driver Version Windows

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#49]
I have been searching for a method to find AMD driver version, to add to online stats. If you see a method, please let me know.

**Comment by davisinfo** [comment]
You can get it from registry HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\000<number>\RadeonSoftwareVersion

In the same location there is a key DriverVersion which is the windows driver version

You can use that to match with what you get running 
 Get-WmiObject Win32_PnPSignedDriver| select devicename, driverversion, classguid | where {$_.devicename -like "*radeon*"}
