### ISSUE TITLE
SWARM - HiveOS name algo

### ISSUE THREAD

**Issue by 0398955** [MaynardMiner/SWARM#8]
Hey. Thank you for the good project. I use swarm in HiveOS. A big request. Make the names of the algorithms in accordance with HiveOS. Because of this, hiveos cannot apply an overclocking profile for the desired algorithm.
example:
SWARM - DaggerHashimoto (name algo)
HiveOS - ETHASH (name algo)
Need to do:
SWARM - ETHASH

**Comment by MaynardMiner** [comment]
I will work on it.

**Comment by 0398955** [comment]
ok. thank.
