### ISSUE TITLE
Windows: Connection to HiveOS.

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/SWARM#87]
It was mentioned by @davisinfo that he was having issues connecting to HiveOS in Windows, though I am unable to reproduce.

He stated the solution was add the line of code:

```
 [Net.ServicePointManager]::SecurityProtocol +='tls12'
```

to SWARM.ps1, ideally right after the parameter list.

**Comment by davisinfo** [comment]
Maybe it is because of my lower version of powershell, they might have new defaults in later versions. What version do you have on windows?

**Comment by MaynardMiner** [comment]
```
C:\Users\Mayna\Documents\GitHub\SWARM\build\cmd> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316
```

**Comment by MaynardMiner** [comment]
Regardless, I will add it to the next release. I am just adding it here, so I remember. It's good to add the service protocol to SWARM.ps1 for pools, anyways.

**Comment by MaynardMiner** [comment]
Also, it may not be powershell version, as it is your .Net version that may be problem.
